\LoadClass{beamer}

\usepackage[footheight=1em]{beamerthemeboxes}
\usepackage{listings}

\lstdefinestyle{assignment}{
    basicstyle=\ttfamily,
    keywordstyle=\bfseries\color{blue},
    morekeywords={if,then,else,return,while,do,Input:,Output:},
    commentstyle=\color{Emerald},
    showtabs=true,
    numbers=left,
    frame=single,
    mathescape=true,
    breaklines=true,
}

\lstset{style=assignment}
